### ISSUE TITLE
Add agent-based adversarial reasoning for decentralized and rplh

### ISSUE THREAD

**Issue by Wzhang3912** [KevinBian107/RPLH#109]
Engineering Details:

decentralized compared to rplh
rplh compared to rplh-social

Evaluation for the social understanding:
1. Successfully finding the spy agent (x_1)
2. Similarity score between HCA's predicted (guessed) attitude and local agent's true attitude  (x_2)

Evaluation of the system:
1. Convergence rate (y)

**Comment by KevinBian107** [comment]
Fron latest testing, the model can perfectly find who is the spy if incrementally thinking about each agent. However, spys doesn't show up too often sometimes, so maybe after there are both no box and no targets in the spy grid, we reveal in prompt that that grid is spy?

**Comment by KevinBian107** [comment]
Currently appended information to system messages

**Comment by KevinBian107** [comment]
Maybe adding descriptive agents?
