### ISSUE TITLE
Make action check + synthetic check function together Or better RE

### ISSUE THREAD

**Issue by KevinBian107** [KevinBian107/RPLH#25]
- [ ] Make action check + synthetic check function together, prevent more unneccessary conversation and hellucination

- [ ] Develop a better regular expression system that is less prone to error

Write a function for RA such that:
- Need to make sure that this better RA satisfy many conditions (i.e. when model give just " or just }) and have a default setup for when RA is not met (we remove the json check completely)

- The agent format should be hard coded (i.e. Agent[0.5, 0.5]) then remove agents that doesn't do an action to minimize the place for error (all we need from the model is the action they said).

- Write it in a way that it is scalable.

- Json checker causes a lot of issues. Once the agent enters a json check, it is stuck in it, json check problematic

This is the most important step currently, then later we can start running, the system has the ability, but just the syntheic check is very anoying

**Comment by KevinBian107** [comment]
Develop a better regular expression system that is less prone to error

**Comment by KevinBian107** [comment]
Seems like after adding history, there is weird synthetic check issue, may be caused by history disturbing the agent

**Comment by KevinBian107** [comment]
Must have execute after each time running or else the system may pick up something that actually belongs to the rpompt

**Comment by Wzhang3912** [comment]
Regular expression response flow:
- Check for curly brackets in raw response
- Extract the last set of curly brackets as final actions from raw response
- Use regular expression to extract agent+action information, then put the information back in JSON format
- The response is then passed into syntactic check function.

**Comment by Wzhang3912** [comment]
Syntactic check always failed at second round => we might need to look at how we incorporate dialogue history into prompt.
