### ISSUE TITLE
RPLH-efficient Better Environment Representation

### ISSUE THREAD

**Issue by Wzhang3912** [KevinBian107/RPLH#46]
Change state representation from, for instance, `"0.5_0.5": ["box_red"]`, to `"0.5, 0.5": ["box_red"]`

**Comment by KevinBian107** [comment]
Environment representation only effects the state-action-history prompt

**Comment by Wzhang3912** [comment]
Thus, we can change the state-action-history prompt directly without modifying the existing environment.
